apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-3-300
  labels: 
    netRequest: '300'
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
            cpu: 100m
            memory: 100Mi
        requests:
            cpu: 100m
            memory: 100Mi
    
