apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    netRequest: "100"
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
            cpu: 100m
            memory: 100Mi
        requests:
            cpu: 100m
            memory: 100Mi
