apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
profiles:
  - schedulerName: concurrent-scheduler
    plugins:
      preFilter:
        enabled:
          - name: ConcurrentScheduling

  - schedulerName: default-scheduler


