apiVersion: v1
kind: Pod
metadata:
  name: 27-1500m-2000mi-20mb
  labels:
    netRequest: '20'
spec:
  containers:
    - name: nginx
      imagePullPolicy: Never
      image: nginx:latest
      resources:
        limits:
            cpu: 1500m
            memory: 2000Mi
        requests:
            cpu: 1500m
            memory: 2000Mi
    
